### ISSUE TITLE
不支持mysql bit类型

### ISSUE THREAD

**Issue by QuaidChen** [Mikaelemmmm/sql2pb#1]
2022/04/06 15:01:37 no compatible protobuf type found for `bit`

**Comment by Mikaelemmmm** [comment]
bit我用的少，一般都用tinyint替代？  bit 对应protobuf 什么类型好 ，int ? bool ?

**Comment by Mikaelemmmm** [comment]
> 2022/04/06 15:01:37 no compatible protobuf type found for `bit`

bit我用的少，一般都用tinyint替代。 bit 对应protobuf 什么类型好 ，int ? bool ?

**Comment by Mikaelemmmm** [comment]
mysql 的bit我用的少，基本都用tinyint代替了，它对应protobuf哪个类型好点？bytes ？ int？bool？ 我来支持下

**Comment by Mikaelemmmm** [comment]
> 2022/04/06 15:01:37 no compatible protobuf type found for `bit`

mysql 的bit我用的少，基本都用tinyint代替了，它对应protobuf哪个类型好点？bytes ？ int？bool？ 我来支持下

**Comment by QuaidChen** [comment]
bool好些

**Comment by Mikaelemmmm** [comment]
> bool好些

ok

**Comment by Mikaelemmmm** [comment]
https://github.com/Mikaelemmmm/sql2pb/pull/12
