### ISSUE TITLE
为什么我生成的中文是乱码

### ISSUE THREAD

**Issue by zhitunAI** [Mikaelemmmm/sql2pb#10]
//--------------------------------鑺傜偣琛?-------------------------------
message SysAuthRule {
  int64 id = 1; //id
  SysAuthRuleType type = 2; //menu涓鸿彍鍗?file涓烘潈闄愯妭鐐?  int64 pid = 3; //鐖禝D
  string name = 4; //瑙勫垯鍚嶇О
  string title = 5; //瑙勫垯鍚嶇О
  string icon = 6; //鍥炬爣
  string url = 7; //瑙勫垯URL
  string condition = 8; //鏉′欢
  string remark = 9; //澶囨敞
  int64 ismenu = 10; //鏄惁涓鸿彍鍗?  SysAuthRuleMenutype menutype = 11; //鑿滃崟绫诲瀷
  string extend = 12; //鎵╁睍灞炴€?  string py = 13; //鎷奸煶棣栧瓧姣?  string pinyin = 14; //鎷奸煶
  int64 weigh = 15; //鏉冮噸
  string status = 16; //鐘舵€?}

文件格式编码是utf16？？？

**Comment by feng99** [comment]
windows下的默认cmd是GBK，建议改一下编码UTF8，或者用git bash就可以了
