### ISSUE TITLE
部分message 没有”}“

### ISSUE THREAD

**Issue by zhitunAI** [Mikaelemmmm/sql2pb#11]
message SearchWaxAccountGroupReq {
  int64 page = 1; //page
  int64 pageSize = 2; //pageSize
  int64 id = 3; //id
  int64 pid = 4; //娓告垙ID
  string name = 5; //缁勫悕
  string rules = 6; //璐﹀彿缁?}

message SearchWaxAccountGroupResp {
  repeated WaxAccountGroup waxAccountGroup = 1; //waxAccountGroup
}

生成后文件没有SearchWaxAccountGroupReq “}”

**Comment by Mikaelemmmm** [comment]
windows下cmd默认编码有问题，windows下cmd默认编码是gbk，改成utf8或者使用git bash
