### ISSUE TITLE
是否可以过虑某些字段

### ISSUE THREAD

**Issue by ysfzf** [Mikaelemmmm/sql2pb#4]
是否可以加一个参数，用来过虑某些字段，如created_at,updated_at,deleted_at......谢谢

**Comment by Mikaelemmmm** [comment]
这个默认我已经过滤了create_time、update_time 、version等 ，这个我看看怎么暴露一下

**Comment by Mikaelemmmm** [comment]
https://github.com/Mikaelemmmm/sql2pb/releases/tag/v1.0.3

**Comment by Mikaelemmmm** [comment]
> 是否可以加一个参数，用来过虑某些字段，如created_at,updated_at,deleted_at......谢谢

https://github.com/Mikaelemmmm/sql2pb/releases/tag/v1.0.3
