### ISSUE TITLE
生成的方法名有点小问题

### ISSUE THREAD

**Issue by bbmeme05** [Mikaelemmmm/sql2pb#7]
```  //-----------------------address-----------------------

  rpc AddAddres(AddAddresReq) returns (AddAddresResp);

  rpc UpdateAddres(UpdateAddresReq) returns (UpdateAddresResp);```

表名Address ，生成的方法里面少了个s

**Comment by Mikaelemmmm** [comment]
我晚点确认下，这个不知道是不是关键字什么导致的

**Comment by Mikaelemmmm** [comment]
> ```
> 
>   rpc AddAddres(AddAddresReq) returns (AddAddresResp);
> 
>   rpc UpdateAddres(UpdateAddresReq) returns (UpdateAddresResp);```
> 
> 表名Address ，生成的方法里面少了个s
> ```

https://github.com/Mikaelemmmm/sql2pb/releases/tag/v1.0.4
