### ISSUE TITLE
生成的proto文件不对

### ISSUE THREAD

**Issue by bbmeme05** [Mikaelemmmm/sql2pb#8]
发现生成的proto字段不对，生成到注解里面去了

[![04uON.png](https://s1.328888.xyz/2022/08/08/04uON.png)](https://imgloc.com/i/04uON)

**Comment by Mikaelemmmm** [comment]
windows下的默认cmd是GBK，建议改一下编码UTF8，或者用git bash就可以了

**Comment by bbmeme05** [comment]
学习了，谢谢
